### ISSUE TITLE
Lot label printing issues

### ISSUE THREAD

**Issue by iragm** [iragm/fishauctions#122]
**What gets printed?**
  * For in-person auctions, all non-removed lots, even unsold ones
  * For online auctions, only lots that have sold
**What about multi-location auctions?**
If the auction is multi-location:
  * for online multi-location auctions, the winner's location will appear on the label
  * for in-person multi-location auctions, you'll see a list of all locations (as abbreviations) - the auctioneer will check the winner's location when they write the winner's bidder number on the lot.

**What's been tested?**
Right now, you can either use scissors and packing tape, or print on [Avery 5160 labels](https://www.avery.com/templates/5160) -- these are pretty standard 30 per sheet, 8.5 x 11 labels that you can get from your preferred megacorp like Amazon, WalMart, or Staples.  [Click here to search for them](https://www.google.com/search?q=1+x+2+5/8+labels)

**What else might work?**
There's a ton of options if you go to [auction.fish/printing](https://auction.fish/printing)

I tested a lot of combinations and they seemed to work, but it's entirely possible that something won't work - especially large fonts on small labels, or odd aspect ratios.

**I don't like PDFs**
The old printing system was a web page - it rendered differently on different web browsers, and labels at the end of a page would sometimes be cut in half.  A PDF is necessary for a consistent label layout, and most web browsers can open them just fine.

## Having a problem?  Leave a comment here and I'll take a look at it.

**Comment by kmur** [comment]
Hello, I just set up a test account on your auction.fish.  I would like to print bag labels using a thermal printer.  When I input the label size (2in x 3in) for a single sheet of thermal paper under the custom label size, it allows me to save the settings.  When I try to print under the custom settings, I get an error "Unable to print labels, this is likely caused by an invalid custom setting here".  

My workaround is to copy all the lots and users into Excel, use a lookup function, and MailMerge onto a Word document.  It would be great to have an easier way to print onto paper sheets other than standard sized printer paper.

**Comment by iragm** [comment]
auction.fish is set up to generate a PDF.  I may be able to add support for a thermal printer, or at least export in an easier format for you to work with.

1. What's the model of the printer you are trying to use?
2. What file type (pdf?) does it expect?  Can you provide me with an example?  (If not, no worries.)

**Comment by kmur** [comment]
Hello Ira,

Thank you for your quick response!  The thermal printer I use is a VEVOR
Y468bt
<https://www.amazon.com/dp/B0BWMVNJPX/ref=pe_386300_440135490_TE_simp_item_image>.
Currently I am using MailMerge to print a Microsoft Word Document, example
attached.  I could print to PDF (attached) but I usually print to the
thermal printer directly from the Word doc.  Each page is a 3in x 2in label.

Thanks,
Ken

**Comment by kmur** [comment]
Attachments did not go through.  
[3x2 Label PDF.pdf](https://github.com/user-attachments/files/16462792/3x2.Label.PDF.pdf)
[MailMerge Example SCAPE.docx](https://github.com/user-attachments/files/16462793/MailMerge.Example.SCAPE.docx)

**Comment by iragm** [comment]
Thanks, this is all the info I need for now.  I did a bit of poking and it looks like the PDF generation will be a lot simpler, let me know if you'd greatly prefer a docx.

It will be a few days before I have a chance to put together an update, but I'll let you know once I have something ready to test.

**Comment by kmur** [comment]
That would be great, thank you!  PDF is probably the best format. Docx
format is not consistent across devices.

I don’t know if I should start a new ticket / thread, but it would also be
great or there to be more flexibility in printing labels. Eg. for a user to
print select labels or for an admin to print the labels of multiple users
in one batch.

The use cases would be printing additional labels created after the initial
print run, or replacing damaged labels. The admin may want to print labels
for all users who did not bring labels on a single sheet of paper.

**Comment by kmur** [comment]
An option to print a single label would be great.

What I had in mind was for admins only to be able to print multiple user
labels per page. This would prevent having to use a separe sheet of paper
per user with Avery adhesive labels, which can get expensive.

Eg. If Alice needs 3 labels, Bob needs 1 label, Charlie needs 5 labels,
etc. It makes sense to print everyone on a single sheet rather than a sheet
of 10 or 30 labels per seller.

Ken Murch

**Comment by iragm** [comment]
You can now select Thermal 3x2 as an option at https://auction.fish/printing/

Please give it a try and let me know if you have any suggestions.

**Comment by kmur** [comment]
Thanks, it worked!  I will try printing with the thermal printer when I get
home this evening.

Would it be possible to configure the system to allow users to choose which
fields to add to the label?  Labels of different sizes have more space for
additional fields such as the description, donation (Y/N), QR
code, category, auction name (or date), reserve price, seller email, etc.

Thanks,
Ken Murch

**Comment by iragm** [comment]
> An option to print a single label would be great.

This has been added to the lot page.  I don't know where else it would be useful to add -- maybe on the lot admin dialog?

> What I had in mind was for admins only to be able to print multiple user
labels per page. This would prevent having to use a separe sheet of paper
per user with Avery adhesive labels, which can get expensive.
>
> Eg. If Alice needs 3 labels, Bob needs 1 label, Charlie needs 5 labels,
etc. It makes sense to print everyone on a single sheet rather than a sheet
of 10 or 30 labels per seller.

There's the option to print blank labels at https://auction.fish/printing/.  A couple people asked for it to solve this exact use case, but right now I don't think anyone is using it at all.  (Haven't pulled the stats on that though.)

I have added a new page for auction admins:  if you select **More > Print Unprinted Labels**, this will do exactly what you'd expect.

> Would it be possible to configure the system to allow users to choose which
fields to add to the label?  Labels of different sizes have more space for
additional fields such as the description, donation (Y/N), QR
code, category, auction name (or date), reserve price, seller email, etc.

I am "familiar" (to put things diplomatically) with how tech savvy the average user on the site is.  Options are extremely confusing to people.

Labels are designed to print only the necessary information:

- If a lot is sold, the winner's name goes on the lot, not the seller's name
- If there's a reserve set that is higher than the auction's minimum bid, reserve price will appear (unless the lot is sold)
- If there's a buy now price set on the lot, it will show up (again, unless the lot is sold)
- If there's multiple locations in the auction, the locations will appear so you can check where the lot is going.
- etc.

Adding additional text like the date, auction, etc., is interesting and I get why it's important for record keeping purposes, but at the auction itself, it will just create confusion.  I saw your example labels and they're quite nice, but I am trying to keep things as simple as possible.

QR codes are a special case, I intended them to allow you to go to the lot and see more information, but NO ONE uses them.  Last time I pulled the stat for it, a total of 0.02% (that's 0.02%, not 2%) of all lots had had their QR code scanned.

I removed the QR code from the thermal labels to save space, and it's very likely that I'll remove them from all labels in the future, since the most common suggestion I get about labels is to make the text larger so it's easier to read.  If you were a cichlid club instead of a kilifish one, you'd get these same complains :)

Of course - if there is information missing from the label that you feel is critical, drop a comment here.

**Comment by kmur** [comment]
Thank you again for the quick responses.

I tried printing blank labels on the Avery template but they are truly blank..  It's good for reusing partially used Avery sheets, but it's a very specific use case and would require the admin to configure the setting for each partial sheet loaded into the printer tray.  I think it would be more useful if the admin had the ability to see how many labels each seller has and use checkboxes to select multiple sellers to print.  Using a thermal printer avoids this issue by printing one label per page.

I agree the tool should be as simple as possible for most users.  Good defaults go a long way to making the experience trouble free and I think you've achieved that well.  I think it would balance simplicity with flexibility if an admin could select fields to create a custom label for their club's needs.  This could be set up in the custom label configurator, which is unlikely to be used by most casual users.

<img width="1028" alt="auction fish custom labels" src="https://github.com/user-attachments/assets/0267c040-b81e-4c4e-9ee2-56813acfb59f">
 
One use case for adding a field is requiring sellers have email or phone.  Buyers sometimes want to contact the seller to replace losses, ask for care tips, or simply to build connections.  Often the club's admin or leadership become the "nerve center" for contact info requests that could be directly between the buyer and seller.  Additionally, larger labels such as Avery 18262 or 3x2s have space to include a description field, while the small Avery 5160s should be limit fields to the minimum.

**Comment by iragm** [comment]
All great points.  But this would need to be configured and standardized on a per-auction bases, so if Bob has large Avery labels, but Alice only has small ones, their labels will be different (and inconsistent), making print-from-home confusing.  Right now, the consistency is very important, with a couple of clubs requiring that all lots be preregistered online and doing no registration or label printing at the door.

If this is something that's important to you, let's reevaluate after you've run a couple auctions and get some feedback from your club members.  I'm not strictly opposed to it, but it'll probably take the better part of a week of my time to put together, document and test, so it is a project.

> Often the club's admin or leadership become the "nerve center" for contact info requests that could be directly between the buyer and seller.

Anecdotally, one of the only bad experiences I've had running auctions was giving people each other's contact information to sort out an issue with a lot.  It ended with someone leaving the club.  Having the club's admin mediate this sort of issue is a huge advantage IMHO.  But I recognize that each club is different and has different needs.

**Comment by iragm** [comment]
Bulk label printing has been added for in-person auctions.  I'm closing this for now, but please reopen if you have further suggestions or find issues.
