### ISSUE TITLE
Print Labels for Lots - Page Not Found

### ISSUE THREAD

**Issue by CraigS2** [iragm/fishauctions#125]
In the recent TFCB 2022 auction I can print my invoice no problem but when clicking on 'Print Labels for Lots' the link is bad and a 'Page Not Found' result.

**Comment by iragm** [comment]
Your link should be this one: https://auction.fish/invoices/1712/labels

Are you signed in?  Did you access your invoice via the email notification, or via https://auction.fish/invoices/ ?

**Comment by iragm** [comment]
Should be good - this would happen if the user wasn't signed in, and accessed their invoice via the no-login uuid link.  You can now print labels using the same no-login link.
