### ISSUE TITLE
Auction List - Mixing Live Auctions with Virtual Auctions is confusing to users

### ISSUE THREAD

**Issue by CraigS2** [iragm/fishauctions#130]
The existing list of auctions which includes pending, active, and past auctions is helpful. I like it a lot. However in 2022 and early 2023 some auctions appeared in the list that were confusing, as they were not pending virtual auctions but placeholders for live auctions with a different workflow and user experience. Currently the pending NEC auction is an example. Another example is the PVAS Nov auction, which I actually participated in at the Nov meeting. 

There are many ways to resolve this issue.  At its core, these auctions appear very similar but IMO have enough differences to merit careful separation of workflows. For example a live auction needs only a bidder/seller ID not necessarily a full login to the auction.fish site. For those browsing the pending or active auctions, it's disappointing to discover you may be looking at an auction you cannot participate in without being at a live event. While I see an option to 'hide' auctions from the list, I am suggesting more of a separate list and associated workflow. For example at live auctions the data entry to capture all seller/bidder IDs and LOT numbers and then efficently manage the checkout process is critical to success, as these are typical bottleneck points in live auctions. These pain points are less critical in a virtual auction, which of course rely on much greater detail for lots offered and use a time window where auction.fish users can participate.

**Comment by iragm** [comment]
A lot of discussion of the workflows and behind-the-scenes stuff happened as part of #103.  In terms of managing and running a live auction, it's now quite simple and works smoothly (suggestions always welcome of course).  Extensive improvements have been made as recently as a month ago.

It's important IMHO to keep both types of auctions in the list -- it's a great way for clubs to advertise their auctions.

That said, this is definitely confusing for the end user on the site.  I've added a new option at https://auction.fish/preferences/ to allow you specify the in-person auction distance separately, as well as a new indicator on the auction list to differentiate online auctions.

Additional suggestions are welcome -- please add them here!
