### ISSUE TITLE
Admin cannot directly edit buyer or mark a lot as unsold after it's been sold

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#176]
I am running a test auction as an admin.  I am able to set lot winners of unsold lots, but editing the sold lot is not working well.  When I mark the lot as as "unsold" the status does not save.  

The workaround I found allows me to assign the sold lot to another winner from the "Set Lot Winners" page, then mark the lot as unsold when the site returns the error prompt saying the lot has already been sold. 

When I click into the individual lot view the dropdown for the lot winner does not display (tried on Safari, Edge, and Brave browsers). Interestingly, I am able to edit the sold price from this view. I cannot assign it or to assign another winner from this view.

Screenshots attached
<img width="1076" alt="auctionfish reassign lot to another winner to mark as unsold" src="https://github.com/user-attachments/assets/53e407d0-83b7-4477-bab4-413a431c463c">
<img width="940" alt="auctionfish lots after edit" src="https://github.com/user-attachments/assets/448d13df-56e8-456b-a90e-0f3a0ce30718">
<img width="1076" alt="auctionfish save as unsold" src="https://github.com/user-attachments/assets/047f8932-0b12-41ab-a1fa-1fd9b4bcf2b0">
<img width="599" alt="Edit lot auctionfish" src="https://github.com/user-attachments/assets/dadf91dc-5530-4a92-8691-da4e5c3d2390">

**Comment by iragm** [comment]
This was broken in the update I pushed out less than an hour ago -- great work catching it so quickly!  It is now fixed and should work correctly once the cloudflare cache expires.  Please give the changes a few hours to propagate and then test again.

**Comment by kmur** [comment]
Thanks for the quick fix! One more edit is on the "Set Lot Winners" view, the button "mark lot as unsold" is not updating

<img width="1144" alt="fishauction mark as unsold not updating" src="https://github.com/user-attachments/assets/77096356-8379-4250-9053-2c6aa5fac31c">

**Comment by kmur** [comment]
A minor UI issue when selecting the lot winner.  The window obscures the first few options on the dropdown.  I replicated this on two browsers - Brave and Edge 

<img width="593" alt="auctionfish lot edit dropdown obscured" src="https://github.com/user-attachments/assets/2e1c5fd6-488d-40a0-8ba6-bc6fe126662b">

**Comment by iragm** [comment]
> Thanks for the quick fix! One more edit is on the "Set Lot Winners" view, the button "mark lot as unsold" is not updating

This seems to be working correctly to me -- it's supposed to simply end the lot without a winner, which it does.  If it's still not working, let me know.  This issue is unrelated to the lot winner drop down on the manage this lot page.

**Comment by iragm** [comment]
This all looks good to me now.  Please reopen if you run into any more issues.
