### ISSUE TITLE
Reporting auction results for admin use

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#177]
I completed a test auction and found it difficult for the admin to get a summary of sales to determine how much the club made in the auction.  I think the reporting could be improved in a few areas:

1. When exporting lots as a .csv file, there are columns for the seller and for the buyer, but sales price, club cut, and seller's cut should be added per lot sold. 

2. When exporting users as a .csv file, total bought and total sold are listed per user, but the total sold is the seller's cut after club commissions.  I suggest total sales be the total sales price of the items, and columns added for club cut and seller's cut

3. On the user invoices total the value of the items sold, club commission, and seller cut.  Currently the "total sales" is the seller cut after club commission.

4. On the summary stats page, there is a bug in the total commissions after adjustments.  Screenshot attached.  The test auction I used has a commission of 15% and no donated items.  I verified the sales totals and club commissions but adding the individual invoices.  

<img width="1052" alt="auction summary stats" src="https://github.com/user-attachments/assets/9a999bff-a574-47ec-9448-1fcd29405de6">

5. It would be nice to show the total value and category of adjustments such as "rounding" and "club donation" on the summary page.  In the case of donations, this should be on the user invoice as a total in addition to the note on each donated line item.

**Comment by iragm** [comment]
> When exporting lots as a .csv file, there are columns for the seller and for the buyer, but sales price, club cut, and seller's cut should be added per lot sold.

This is a good suggestion.

> When exporting users as a .csv file, total bought and total sold are listed per user, but the total sold is the seller's cut after club commissions. I suggest total sales be the total sales price of the items, and columns added for club cut and seller's cut

Also a good suggestion.

> On the user invoices total the value of the items sold, club commission, and seller cut. Currently the "total sales" is the seller cut after club commission.

I don't want to make it super obvious to users how much the club is taking.  It's a delicate subject -- most clubs take a 30%-50% cut and people often don't make the connection between 30% and $30 out of every $100.

I did change the total to total payout to make it move obvious what the number is.

> On the summary stats page, there is a bug in the total commissions after adjustments. Screenshot attached. The test auction I used has a commission of 15% and no donated items. I verified the sales totals and club commissions but adding the individual invoices.

I am not seeing this issue (?)  I rechecked the stats for a couple auctions, and they seem right to me.  Your auction does have a donation in it, which may account for the difference.  Please reopen this issue if the numbers don't seem right and I'll take another look.

> It would be nice to show the total value and category of adjustments such as "rounding" and "club donation" on the summary page. In the case of donations, this should be on the user invoice as a total in addition to the note on each donated line item.

Donation total is an excellent idea, that has been added.  I don't want to put too much information there, the stats aren't intended supposed to be "a way to audit the other stats" but rather a general overview of your auction.

**Comment by kmur** [comment]
Thank you for the quick updates!

I was doing quite a bit of auditing just to make sure everything adds up, and had a bit of tunnel vision in that aspect.  

One minor fix is on the .csv export for lots, some of the values under club cut were formatted as text (has a ' before the digits).  This is something easily fixed in Excel, but might confuse people when the totals don't add up because some entries are values and others are text. 

![Screenshot 2024-08-14 092930](https://github.com/user-attachments/assets/dcc56adf-320b-48f7-8a53-ebf0c2405bf2)

**Comment by iragm** [comment]
Should be fixed now.  I haven't used Excel in a long time, I do all CSV testing in Google sheets, so let me know if it's still not working.

**Comment by kmur** [comment]
I believe the issue is because there is a very small error in the calculation that is rounded off by Google Sheets but not Excel (unless I select the option to convert the .csv file).  Screenshot of the csv text attached and excepts pasted below.  

Sell price,Club Cut,Seller cut
14,2.0999999999999996,11.9
12,1.8000000000000007,10.2
8,1.2000000000000002,6.8

<img width="208" alt="csv calculation error" src="https://github.com/user-attachments/assets/5dbb66b6-0a96-477c-a331-725fc8ba60bb">

**Comment by iragm** [comment]
Are you looking at a file downloaded in the last ~20 minutes?  The club and seller cut numbers should now be rounded to two decimal points.

**Comment by kmur** [comment]
Agreed that rounding to the nearest cent is the best solution.  There is an error on the 15th or 16th digit (quadrillionth) which is material only because it causes formatting issues. 

I just downloaded the .csv file again, but some of the calculations are still not rounded.  I will try again later today in case it's a cache issue.

**Comment by iragm** [comment]
This is not something that can be cached, it's generated on the fly when you request it.  All the values for your test auction are rendered to two decimal points when I download the file, let me know if anything else needs to be changed.

**Comment by kmur** [comment]
It's still showing values beyond two decimals when I open on a text editor, but only for certain calculations. 

You might be able to reproduce it in a test auction if you have a 15% commission on a $14, $12, and $8 item.

**Comment by iragm** [comment]
Oops, I was looking in the wrong place.  **Now** it should be fixed.

**Comment by kmur** [comment]
I downloaded again and it's fixed now.  Thanks!
