### ISSUE TITLE
Request to set reserve price at $1, and to allow the admin to override the reserve price

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#181]
I noticed the minimum price an item can be listed or sold for is $2.  I would like to lower it to $1. 

I would also like to have the option for the auctioneer (admin) to sell an item below the reserve price.  This should launch a prompt (reserve price is $x, are you sure you want to sell for $y).  This is nice to have for in-person auctions where there is no bidder and the seller asks or allows the auctioneer to lower the price (eg some of the fish in a bag died).

**Comment by iragm** [comment]
This is a good suggestion.  Admins can already sell lots for any price, the reserve price is shown on the set lot winners page when you enter the lot number.  A redesign of the set lot winners process is planned at some point.

**Comment by kmur** [comment]
Thanks, I was able to set the sale price as $1 as an admin.  I see the reserve price is shown on the item, so the the admin should notice it during a live auction.  

I think it might be a good idea to have a prompt if the admin sets the sales price below the min/reserve, but this would be a minor safeguard / refinement.
