### ISSUE TITLE
Proxy bidding on an in-person auction

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#189]
Our club does in-person auctions but allows for proxy bidding from members who cannot attend or select representatives from other clubs.  We take proxy bids on and assign a member to bid on behalf of the proxy bidders, but this often results in missed bids.  I would like to suggest combining some aspects of virtual auctions with in person auctions

1. Allow members to submit (and withdraw) bids online before the auction starts
2. Allow non-members / affiliates approved by the admin to submit and withdraw proxy bids before the auction starts 
3. Virtual bids would "bid up" to $1 over the next lowest virtual bid. and the winning bid would be visible to all users
4. Under set lot winners show the max proxy bid amount and bidder

Thoughts on having an option in the auction rules for a hybrid auction with online pre-bidding and proxy bidding?

**Comment by kmur** [comment]
5. The item to show bidding history and current max bidders 1st, 2nd, 3rd.  If the max bidder withdraws it would go to the 2nd bidder, and so on.  
6. On the item page suggest similar items.  Eg. If there are multiple lots of the same item the item page should suggest matching lots.

**Comment by iragm** [comment]
> Our club does in-person auctions but allows for proxy bidding from members who cannot attend or select representatives from other clubs. We take proxy bids on and assign a member to bid on behalf of the proxy bidders, but this often results in missed bids. I would like to suggest combining some aspects of virtual auctions with in person auctions
> 
>     1. Allow members to submit (and withdraw) bids online before the auction starts
> 
>     2. Allow non-members / affiliates approved by the admin to submit and withdraw proxy bids before the auction starts
> 
>     3. Virtual bids would "bid up" to $1 over the next lowest virtual bid. and the winning bid would be visible to all users
> 
>     4. Under set lot winners show the max proxy bid amount and bidder
> 
> 
> Thoughts on having an option in the auction rules for a hybrid auction with online pre-bidding and proxy bidding?

This is already implemented, almost exactly as you describe, but it's been disabled.  My club ran two auctions like this and we found it incredibly confusing.  Everyone hated it.

**The show-stopper for us is that in-person bidders have a huge advantage over online people.  They can see the lot in question and more accurately value it.  And, they can decide if they want to keep bidding over the online person or not.**

My club ran these with people being able to bid online and then continue bidding in person.  This drove up the price for anyone who bid online, and they often arrived to see the actual item and were disappointed to win it.

Delivering lots is also a bit of an issue -- how does your club handle it?

> The item to show bidding history and current max bidders 1st, 2nd, 3rd. If the max bidder withdraws it would go to the 2nd bidder, and so on.

Why should people be allowed to withdraw bids?

> On the item page suggest similar items. Eg. If there are multiple lots of the same item the item page should suggest matching lots.

This is already done (I think).  You should seen other unseen lots when viewing lots in your auction.  See [this](https://auction.fish/faq#how-do-recommended-lots-work)

**Comment by kmur** [comment]
_Delivering lots is also a bit of an issue -- how does your club handle it?_

- For members in the local area, it is common for people to arrange for an attendee to deliver the item or bring it home so the absent member can collect it
- We ship fish to bidders and clubs outside of the local area.  To save on shipping costs, non-local clubs will combine their won items into a single shipment (eg. the the Killifish Club of Houston gets one box, the Phoenix club gets another box)

_Why should people be allowed to withdraw bids?_
- Allowing withdrawn bids before the auction start allows members to budget their spend as recently added items appear.  I can see how this could be abused, but the downside is limited because items would still be auctioned live in an attempt to surpass the max bid

I think your experience with pre-bidding and proxy bidding is informative.  I understand there is an advantage for anyone who shows up in-person to an auction but I would not call it unfair.  

Our club and a few other killifish clubs do proxy bidding already with pen and paper.  It is a highly manual process but it has been done for many years. We ask bidders to fill out a form listing lot numbers and their max bid (example attached). 

![Screenshot 2024-08-28 163215](https://github.com/user-attachments/assets/3d2d16d9-2d08-49e5-8805-b7d506c15f10)

**Comment by kmur** [comment]
_On the item page suggest similar items. Eg. If there are multiple lots of the same item the item page should suggest matching lots.

This is already done (I think). You should seen other unseen lots when viewing lots in your auction. See [this](https://auction.fish/faq#how-do-recommended-lots-work)_

I looked at the way the site is matching lots by category.  This is a good start, but the real intention is to surface duplicate items.  I think this can be done by searching for keywords in the lot name and returning the best matches. Eg. if I am looking at a bag of Vallisneria, I would like to see all the other lots with Vallisneria or similar names like "Val", rather than the category of "Aquatic Plants"

**Comment by kmur** [comment]
> _Why should people be allowed to withdraw bids?_
> 
> * Allowing withdrawn bids before the auction start allows members to budget their spend as recently added items appear.  I can see how this could be abused, but the downside is limited because items would still be auctioned live in an attempt to surpass the max bid

Allowing people to withdraw bids until the auction start seemed the closest to matching the manual process of the auction admin receiving submissions of proxy bids and corrections. 

Final proxy bids are due before the auction start.  If an early version was submitted it is allowed to be modified before the deadline / start of the live auction.

**Comment by iragm** [comment]
Against my better judgement, I've re-enabled the checkbox.  I think that it will take some major changes to get it working, but please play around with it.

One more question about how you'd like to see this work, consider this example:

Online user A bids $5
Online user B bids $10

On the set lot winners screen, the auctioneer shows a picture of the lot.  The in-person bidders can see this screen, and the auctioneer recording bids.

Right now, that screen will say "max online bid: $6 bidder number [online user B's bidder number]" 

If that screen lists the top 3 bidders and their max proxy bids, the joker in the back will bid up to $1 below their proxy bid.  Lame.

If that screen works as it does now, then someone in the audience can bid $8 and win the lot, even though online user B was willing to bid 10.

Possible fixes:
- The auctioneer can click a button to reveal the max bid
- The auctioneer can enter each and every in-person bid and the system will show if they've been outbid or not
- An auction admin in the audience can see the max bid and bids on behalf of people online
- Or something else

**Comment by iragm** [comment]
> I looked at the way the site is matching lots by category. This is a good start, but the real intention is to surface duplicate items. I think this can be done by searching for keywords in the lot name and returning the best matches. Eg. if I am looking at a bag of Vallisneria, I would like to see all the other lots with Vallisneria or similar names like "Val", rather than the category of "Aquatic Plants"

This is exactly how it works.  It even prioritizes lots from the same seller. The following words don't get used for matching, but all other words in the lot name do.
```
# the following words are very common and should not be used when generating recommended lots or assigning categories
IGNORE_WORDS = ['albino','red','blue','pair','super','fish','black','breeding','group','fry','female','water','male','trio','green','lot','fin','yellow','gold','large','donation','young','filter','white','fire','blood','and','orange','bag','qty','juvies','starter','adult','hardy','with','small','size','breeders','brown','breeder','pack','two','pink','proven','better','than','more','adults','inch','from','wild','bunch','superb','the','double','reverse','new', 'test']
```

If this is not working, can you please open a separate issue for it?

**Comment by kmur** [comment]
Thanks, I will do thorough testing before using in a "live" auction

In your scenario, I think two of your proposed solutions would work well

> The auctioneer can enter each and every in-person bid and the system will show if they've been outbid or not
> An auction admin in the audience can see the max bid and bids on behalf of people online

On the lot winners page visible to the audience the the screen show current max bid at $6 ($1 over the second highest bid), but allow members to bid up the price without knowing what the max bid amount.  One way of doing this would be a message the the set lot winners page eg "Bidder B submitted a higher bid" until in-person bids stop, or the proxy bid is exceeded.  Keeping the max bid hidden protects Bidder B from overpaying due to insincere bids from the members in the in-person auction.

Additionally, an admin should be able see the max bid on the item page and bid on behalf of the proxy bidder to help speed up the auction.

**Comment by iragm** [comment]
OK, this seems doable.  I'm still not convinced it's a good idea, but it's not hard to implement.

I imagine the next thing you will want is multiple pickup locations (including a "mail me my lots") option for in-person auctions, another removed feature :)  When testing, think about what you want the invoice to look like for online bidders, and if the system as-is (1. add invoice adjustment, 2. export CSV 3. send Paypal Batch Invoice) will work for you.

One other club has requested hybrid auctions recently.  I have reached out to them via email to see if they can weigh in on this thread.

It's going to be at least a couple weeks before I have a chance to work on this - I am trying to finish up some tutorial videos covering how to use the site.

**Comment by kmur** [comment]
Thanks Ira,

I will do due dilligence testing and get back to you on any issues I see. My end goal isn’t so much virtual auctions, but improving proxy bidding in live auctions. 

I am not interested in having the software assign pickup locations but this could be useful for other clubs. Members who are absent but getting fish are pretty good about making arrangements to pick up fish from other members who could attend. 

Using Pirateship or Shipstation, UPS ground is also very affordable and delivers the next day if within a couple hundred miles. A few months ago I sent a box of fish (8x10x15 6lbs) about 100 miles for less than $10, delivered the next day.

**Comment by iragm** [comment]
Here's what we've got so far:

When you check online bidding, new fields show up in the auction rules
- date start
- date end
- only approved bidders
- delete bids (#191)

Setting winners:
- This is the same as for in-person but with a twist:
- You can't set the winner if the winning price is less than an online bid
    - This is a hard block not just a warning; you can always use the lot admin (edit lot) dialog
- There's a one click button to set the winner -- click save, then sell to (online bidder) for (online high bid).  Which I guess is technically two clicks if you want to be pedantic.
- There are buttons on the lot page, lot admin dialog, and on the set winners screen to show the max bid.  To keep things "fair" for users, revealing the winner will create a lot history showing who revealed it.  If users see that an admin is peeking at the max bid and then outbidding them, they can (rightfully) get upset.

There are some interesting uses interactions with buy now:
- When buy now is used, the winners are set automatically and the lot is added to the invoice
- If you set buy now to required, and disable bidding, you can have people buy now stuff online, and skip bidding altogether.  This does not show up in your rules (by design), it's up to you and your auctioneer to respect this or not.  So you can pre-sell stuff online, then get to the auction and auction the remaining items off.

Considerations:
- Dates in the main list of auctions don't show the online bidding dates
- Dates in promotional emails don't use the online bidding dates
- Right now you cannot set an unsold lot fee on an in-person auction, this just seems like asking for trouble because someone will bring in a bag of duckweed, and then you're going to charge them a dollar to throw it out?  Plus lots get lost, fish die mid auction, etc., it's just a lot of bookkeeping
	
Given the scale of this feature, I'm sure there's stuff that will need to be changed.  I'll leave this open for a few days to collect feedback, but even if it's closed you're always welcome to leave a comment here.

**Comment by iragm** [comment]
Right now, there's no warning if you try to sell something for more than someone has bid online.

That is, bidder 101 can bid $10 online, and then you can mark the lot as sold to bidder 101 for $20 with no warning or other "friction".

This seems like the right way to do things, as often online bids get placed before the auction and then bidder 101 will continue bidding in person, but leave a comment if this seems like it should be changed.

**Comment by iragm** [comment]
Additional issues:
* You should be able to allow buy now before the auction, but not require it for sellers.  Change **Allow online bidding** to be a dropdown menu: Disabled, allow only bidding, allow only buy now, and remove **buy now required, and disable bidding** option.
* When items are sold with buy now before in person bidding begins, if the label is printed, flag it as needing to be reprinted.  (New field required for this.)  Send sellers an email about this.  This is to prevent items that have been pre-sold from going up for bidding again.

**Comment by iragm** [comment]
This is all set, at least for now.  We'll be using it for pre-sales in our upcoming auction, so hopefully it goes smoothly and users don't find it too confusing.

IMHO online bidding on an in-person auction still makes very little sense -- either go all-in and do everything online, or do everything in-person, but this is what the board wanted to go with so we'll see how it goes.
