### ISSUE TITLE
Pre-registration discount is confusing

### ISSUE THREAD

**Issue by iragm** [iragm/fishauctions#190]
People don't understand that "a 10% discount" changes a 50/50 split to a 60/40 split.  This should be more clear in the automatically added rules.

**Comment by kmur** [comment]
I think positioning it as a discount or added fee is confusing to users.  Our club charges 15% but we're setting it at 25% for members who don't add their own item.  

I think it would be clearest to spell it out.

For lots you pre-register on auction.fish, you will be charged 40% of the winning price per lot you sell (60/40 split)
For lots registered by the auction admin, you will be charged 50% of the winning price per lot you sell (50/50 split)

**Comment by iragm** [comment]
Having the term 60/40 split is confusing because users don't know who is getting 60 and who is getting 40.  It seems clear enough without that.

Hopefully people know who the auction admin is.

Alternate language if this is still found to be confusing would be "For lots that are not pre-registered, [...]"
