### ISSUE TITLE
UI for editing lots is inconsistent

### ISSUE THREAD

**Issue by kmur** [iragm/fishauctions#193]
When I am looking at lots as an admin, the UI does not allow me to add photos when I click on the list of lots from the Lots Tab.  I can add or edit a photo when I navigate from the tile view and click "See Details"

![Screenshot 2024-08-29 142137](https://github.com/user-attachments/assets/5fabd6f4-c959-4bcf-955f-9800a1956f40)

From the list view I can click on the carrot to add images for both my own lots and other's lots when logged on as an admin.  I cannot add or edit photos for other's lots when I navigate to the lot from the tile view or lot page on the carrot.

![Screenshot 2024-08-29 142830](https://github.com/user-attachments/assets/89068d20-4884-4c0a-af2a-b780a4d47c9f)

![Screenshot 2024-08-29 143111](https://github.com/user-attachments/assets/43fdd6ca-3b58-44bc-ab1b-81f7541e4998)

**Comment by iragm** [comment]
Phenomenal work spotting this.  Please reopen if not fixed.
