### ISSUE TITLE
Customize what gets printed on a lot label

### ISSUE THREAD

**Issue by iragm** [iragm/fishauctions#238]
This was originally requested by @kmur as part of #122, but it's different enough that it needs its own discussion.
>  Would it be possible to configure the system to allow users to choose which
fields to add to the label?  Labels of different sizes have more space for
additional fields such as the description, donation (Y/N), QR
code, category, auction name (or date), reserve price, seller email, etc.

Another club has requested 
> Would it be possible at some point in the future to be able to customize what prints on the label ?
>
> Example for our auction we would not want the minimum bid – ( everything is minimum bid 1 dollar) to print, but would like the category would be helpful, as scientific name is not an available option. Without digging in more to how you have the report setup ( eg built on a crystal report or similar report building software) to generate the label
>
> Having scientific name added in would help since common names can be all over the place with the names but that is an enhancement request for the future. 

The main issue here is that the requirements need to be set on a per-auction basis, but users print on all different label types.  To illustrate with an example:

Bob adds lots to an auction that requires printing lot number, lot name, quantity, and description.  Bob prints on small Avery labels, which have just enough space for the lot number and name.  **What should happen to the stuff that doesn't fit?**

And related to this, the description field can be up to 10000 characters long, too big to fit on even large thermal labels.  Should it just get cut off?  That seems bad.

Certainly, you can reprint the labels for your users when they arrive, but that defeats a lot of the advantage to preregistering lots.  Comments on this are appreciated.

@jamescurtin what does BAS use/need for labels?

**Comment by kmur** [comment]
> Bob adds lots to an auction that requires printing lot number, lot name, quantity, and description. Bob prints on small Avery labels, which have just enough space for the lot number and name. What should happen to the stuff that doesn't fit? And related to this, the description field can be up to 10000 characters long, too big to fit on even large thermal labels. Should it just get cut off? That seems bad.

Seconding the suggestion that some of the fields can be cut based on the club's needs.  Eg. Our club does not use the Quantity field but it's required. 

A few ideas on accommodating limited space:

- Could there be a character counter on the name and description fields?  Better still, if the user's label defaults should come with a soft character limit it could warn users their text is too long to fit on the label size they've chosen.  Perhaps the "cut off" portion could display in a different color such as red.  An example warning could read something like "the label you selected can fit up to 100 characters in this field, any text in red will not be on the printed label" 
- Can the font dynamically adjust (down to a limit) so longer descriptions can fit into a given space?
- For long descriptions the option to "spill over" onto additional labels.  Eg. Lot 101 (pg 1/3), Lot 101 (pg 2/3), Lot 101 (pg 3/3).

**Comment by iragm** [comment]
Just to give an update on this: The PDF engine used (ReportLab) is an absolute nightmare for label generation, a lot of stuff that seems like it should work (like auto-scaling of Flowables to fit in a table cell) is just plain wrong.  It's likely that my poor understanding of ReportLab is to blame, but ChatGPT doesn't seem to be any more skilled than I am at getting things to work.  I'm ripping it out and replacing it with a different library (WeasyPrint, which has its own set of idiosyncrasies like pinning `pydyf==0.8.0`, but seems pretty solid). 

Given the scale of this change, and that there's several large auctions scheduled for the next few days, I really don't want to break label printing.  So, this is on hold for at least a week, probably two.

> For long descriptions the option to "spill over" onto additional labels. Eg. Lot 101 (pg 1/3), Lot 101 (pg 2/3), Lot 101 (pg 3/3).

This is brilliant, I think it'll take care of things perfectly.  Resizing doesn't really work as people can't read smaller fonts, and the character counter/soft limit will just confuse people.

**Comment by iragm** [comment]
This is now the third major rewrite of label printing.  The following changes have been made:

- Better presets that match (as well as possible) the Avery labels
- Labels can now fill the thermal 3x2 label fully, with no wasted space at the bottom
- The option to print a border around labels to assist those who are printing on paper instead of labels, and failed cutting-things-out in kindergarten
- You can now customize what gets printed for your auction by going to **[your auction] > More > Label Printing > Set what gets printed on labels**.  This option has been deliberately hidden (that is, not put into the dropdown menu) because changing this stuff will inevitably cause confusion and a support ticket.  The defaults are exactly what nearly all clubs want.
- QR codes are now printed on thermal labels.
- For folks like @BillMc577 who want to print the species as well as the common name, I would recommend putting both in the lot name, if they'll fit, or putting the species name in the description field and printing the description field.
- Description field:
    -  The description field prints without formatting (all html tags except newline are stripped) and in a smaller size font than the rest of the text, and will be cut off if it's too long.
    -   I really liked the idea of multiple labels for long descriptions, but automatic page breaks don't work properly in weasyprint and I had to add some code to calculate them manually.
    - Because users can print on all different sizes of label (and even with different font sizes), it's not possible to anticipate what the description field will look like before it's rendered to a PDF.
    - I get it, this is annoying and far from perfect, but I've wasted over a week of my time on this and I'm pretty sick of it.  I will gladly accept pull requests that address this.  Label printing seems to be a project that's approximately the same size and complexity as the entire auction.fish website, and no one seems to have created a python library to make it "just work"
- It's entirely possible to print all the possible fields and run out of space for everything on the smaller labels.  This isn't a problem if you're printing your own thermal labels.

Fun stats: label printing is not very popular.  Only 144 users have printed labels.  Of those:
    * 119 print on large Avery (the default)
    * 12 print on small Avery labels
    * 2 print on thermal 3x2 labels
    * 2 insane people are using custom labels

These data are not entirely accurate because the system does not record who prints the label -- perhaps most people are simply getting their labels printed after they get to the club auction, I know this is the case for our club.

You can definitely still create all sorts of issues with the system as is, for example, a custom lot number that's 9 characters long will run over into the lot name.  No one is currently customizing lot numbers, and I'll probably remove the ability to change them at all in the future.

Still having trouble?  Drop a comment below and see if you can get me to go for a fourth major rewrite of label printing!
