### ISSUE TITLE
Allow high bidder to change max bid

### ISSUE THREAD

**Issue by jbosmith** [iragm/fishauctions#25]
Right now if your max bid is $10 and the actual high bid is only up to, say, $8, you can't change your max. It just tells you that you're already the high bidder. It'd be nice to be able to do that for the "You know, I really want this fish and I don't know if I'll be here at the last minute" type of aha moments.

**Comment by iragm** [comment]
It actually is changing your max bid when this happens.  The blue "You're the high bidder!" message indicates that your bid was successfully updated.

If you try to lower your bid, you'll get a 'You can't bid less than you've already bid' message.

This does bring up an issue though - you can't actually see how much you bid on an item.  I'll try to get that addressed in the next update

**Comment by jbosmith** [comment]
Aha! I thought the number in the txt box was the current highest bid. Good
to know.

**Comment by iragm** [comment]
Next version will have this, changes will be pushed out on Saturday after bidding closes.
![image](https://user-images.githubusercontent.com/71519690/97437297-a2ab7100-18f9-11eb-979e-6aafac04e9bb.png)
