### ISSUE TITLE
Export CSV for bidder's won lots

### ISSUE THREAD

**Issue by whipplesnit** [iragm/fishauctions#267]
I'd like to be able to export a CSV of the lots I've won. Thanks!

**Comment by iragm** [comment]
This is a good suggestion.  What fields would you like?  Maybe:

Auction, Lot number, Lot name, Winning Price, Link to lot

**Comment by iragm** [comment]
There's now a CSV button on the won lots page, here: https://auction.fish/lots/won/

Please leave a comment if you want more fields added.
