### ISSUE TITLE
Sniping protection

### ISSUE THREAD

**Issue by iragm** [iragm/fishauctions#34]
Charge $1 per lot for bids placed in the last half hour of the auction.  Charge $2 for bids placed in the last 15 minutes.

**Comment by iragm** [comment]
An alternative idea: only allow users to place a single bid per lot in the last 2 hours of the auction

**Comment by iragm** [comment]
An alternative alternative idea: prevent this by making it part of the system and charging a fee.

We could have a "hidden bid" checkbox when placing a bid.  This would only be calculated at the end of the auction, and if it beats other bids, it would win.  It would be hidden until the auction ends -- essentially, no different than someone placing a bid at the absolute last second.

We could charge a percent fee for this.

**Comment by iragm** [comment]
This was perhaps the most heated issue in the last auction, so I am reopening this.  Here are some more user comments:

> Funny thing is if users really are entering their max bid, then there's nothing to be upset about. Disappointment yes but if their max was exceeded then they didn't want it enough. But still lots of emotional churn in the end so I get it ... we mostly prefer not to have sniping at all though its pretty natural that there's a lot of bidding on the last day. Funny how perceived value increases when others say it's worth more. Even in real-world auctions there's bidder remorse after the item has been sold (for both winners and losers).

From another user

> It's the worst bidding system in the fish world.
> I have bid and won $300-$400 of auction items [from multiple auctions] and I am [redacted] on Aquabid and this auction has some serious flaws and I won't be participating in the future if it remains this way 
> [...]
> You have to extend the bidding two minutes when a last minute bid is placed.
> It's called horse race style bidding. It's the only fair way to do things 
> [...]
> I would never have even tried to bid had I known that all these people would snipe the end of the auction.
> And there is absolutely no way to keep up when watching 15-20 lots on the screen.
> [...]I was so excited and could hardly wait for March 19th to arrive to start bidding on lots. I wasted so much of my time going back and forth these last eleven days checking on my auction lots.
> 
> I just feel like I 100% wasted all my time on the NEC auction.
> 
> I'm so pissed right now I probably won't even sleep tonight. This just leaves the worst taste in my mouth

As an aside, we use the exact same system that both Aquabid and eBay use for ending auctions - sniping is allowed.

And another user:
> Annoying? 
> 
> "Sniping " as you call it is common place and fair game. If you really want the item you basically have to do that or someone else will.  It's no different than at live auction- that last bid gets the item. 
> 
> I myself waited up to bid late on the things I most wanted because that's just the name of the game. 
> 
>  I didn't realize it was" annoying "

And yet another:

> as someone who participated in this auction for the first time I want to express my displeasure with how the process worked. Last night at 8:30 or a little later I signed off the computer with over $100 worth of bids that had been perfectly stable only to wake up this morning to find that all I had left was $12 of dry goods. I think this needs to be fixed or I have no interest in participating further in auctions of this type with this type of low balling going on.

I also know of a handful of people (perhaps 3-5) who aren't as vocal but simply stopped participating in these online auctions.

**Comment by iragm** [comment]
The proposed fix that I am currently leaning towards is a "rolling" end of the auction - "horse race style bidding".

Lots end at (for example) 8:00 PM as long as there haven't been any bids placed on them in the last 15 minutes.  Each bid that's placed extends the end time by 15 minutes.  This continues for up to an hour, so long as people keep bidding every 15 minutes.

This should be pretty doable from a code perspective, but the politics on this issue make it tricky.  It certainly needs to be optional.

**Comment by iragm** [comment]
Additionally, we need an automatic email to people who place bids but didn't use proxy bidding letting them know that they'll be outbid.

**Comment by iragm** [comment]
Another comment:
> a friend of mine was one of the bitchers lol . I just told him it's an auction . If you really want an item then bid as high as you are willing to spend. End of story 

There are two sides here - one side seems to boil down to:
> I didn't understand how the process worked, I got outbid, and I'm mad

The other side says:
> Lean how online auctions work.  gg ez

Fundamentally, I want people to feel like things are fair.  No one is threatening to leave these auctions if there's sniping protection.  People *have* left the site due to feeling like being sniped is unfair.  Sniping protection will improve auctions overall and it's getting added as soon as possible

**Comment by prmchugh** [comment]
- [ ] Wow there is some serious hostility in the feedback/comments about this. While I would say I fall into the camp of "this is just how auctions work" I think some of your proposed options would work. Does the horse race style bidding really does more than let people know they should bid more at the last minute.

**Comment by iragm** [comment]
This should be all set, pending a few last tests and tweaks.  https://auction.fish/faq#how-exactly-do-dynamic-endings-work

**Comment by iragm** [comment]
Additional feedback
>Your plan [currently live on the site] would be fine. I tend to buy and sell on Ebay, and I have been Outbid in the last seconds of several. It's par for the course. But extending the time, as you suggest, would be fair.
