### ISSUE TITLE
Make images, titles etc. clickable?

### ISSUE THREAD

**Issue by jbosmith** [iragm/fishauctions#40]
Can more than the 'View Details' button be clickable? Maybe even the whole card, but at least the images and titles.

**Comment by iragm** [comment]
Yes, it's trivially easy to make the whole card clickable.  The only reason not to is concern about misclicks, especially on mobile.

**Comment by iragm** [comment]
@jbosmith Consensus from others is that this might be OK on desktop, but bad on mobile.  We need to keep a consistent user experience across platforms (and resizing the window on desktop can't change the behavior of windows), so I don't really see a way to implement this.
