### ISSUE TITLE
Error choosing pick up location 

### ISSUE THREAD

**Issue by malsbury** [iragm/fishauctions#43]
Received the following error when trying to select Chicopee as the pickup location for the PVAS fall auction. 
![Screenshot_20201121-084517](https://user-images.githubusercontent.com/11231720/99878887-7a502300-2bd6-11eb-82d6-6d54a31d8f27.png)

**Comment by iragm** [comment]
Thanks for reporting this, it should be fixed now.  Please reopen this is you're still having trouble.

**Comment by malsbury** [comment]
Successfully registered my locatio choice. Thanks for the quick fix.

All the updates since the annual auction event look great.
