### ISSUE TITLE
Display Watched Item Status in Auction Lot Gallery View

### ISSUE THREAD

**Issue by malsbury** [iragm/fishauctions#44]
It would be helpful to see the yellow watched item star when looking at the gallery view of auction lots. 

For example, if there are multiple lots of the same species added to the auction over time it would be easier to see if a new one was not being watched when scrolling through the listings and/or verify that all are being watched.

**Comment by iragm** [comment]
At one point, I had viewed/unviewed/ended/watched/your lots/lots you bid on all with different color borders, but it was too cluttered to tell what was going on.

Just having the start there is a good idea, let me see what I can do.

**Comment by iragm** [comment]
Check it out and let me know if you think it would be better in a different corner of the tile or anything.

**Comment by malsbury** [comment]
Perfect! Just what I had in mind.

Thanks for implementing it so quickly.
