### ISSUE TITLE
add ability to clone existing auction

### ISSUE THREAD

**Issue by djtrfish** [iragm/fishauctions#68]
For recurring auctions, like monthly meetings.  only auction setup with no lots

**Comment by iragm** [comment]
You got it.  By default, the pickup location date/times are set based on the end date of the new auction.  Generally, clubs end auctions on Friday and pickup is the next day or Sunday, so this will require very little editing, unless you change the TIME your auction ends at.  It's easy enough to edit the pickup location times, anyway.

I have also added a warning when pickup date/times are in the past.
